#library "Erad"
#include "zcommon.acs"
#include "commonfuncs.h"

script 610 (void)
{
    while (CheckInventory("EleenaTauntCooldown") > 0)
    {
        Delay(35);
        TakeInventory("EleenaTauntCooldown", 1);
    }
}

Script 612 (int type) NET
{
	if(CheckInventory("EleenaBallgag"))
	{
		TakeInventory("EleenaBallgag", 1);
		Print(s:"Ballgag Off");
	}
	else
	{
		GiveInventory("EleenaBallGag", 1);
		Print(s:"Ballgag On");
	}
}
