#library "Exhumed"
#include "zcommon.acs"
#include "commonfuncs.h"

script 458 (void)
{
    while (CheckInventory("JonTauntCooldown") > 0)
    {
        Delay(35);
        TakeInventory("JonTauntCooldown", 1);
    }
}

Script 461 (int type) NET
{
	if(CheckInventory("JonBallgag"))
	{
		TakeInventory("JonBallgag", 1);
		Print(s:"Ballgag Off");
	}
	else
	{
		GiveInventory("JonBallGag", 1);
		Print(s:"Ballgag On");
	}
}
