$playersound	TotenkopfPlayer	male	*death			Totenkopf/Death
$playersounddup	TotenkopfPlayer	male	*wimpydeath		*death
$playersounddup	TotenkopfPlayer	male	*crazydeath		*death
$playersounddup	TotenkopfPlayer	male	*xdeath			*death
$playersounddup	TotenkopfPlayer	male	*gibbed			*death
$playeralias	TotenkopfPlayer	male	*pain100		Totenkopf/Hitflesh
//$playersound	TotenkopfPlayer	male	*pain100		bjpain	// Original sound by as3sfxr
$playersounddup	TotenkopfPlayer	male	*pain75			*pain100
$playersounddup	TotenkopfPlayer	male	*pain50			*pain100
$playersounddup	TotenkopfPlayer	male	*pain25			*pain100
$playersound	TotenkopfPlayer	male	*grunt			bjoof
$playersound	TotenkopfPlayer	male	*usefail		bjnope
$playersounddup	TotenkopfPlayer	male	*land			*grunt
$playersound	TotenkopfPlayer	male	*taunt			bjtaunt
$playersound	TotenkopfPlayer	male	*evillaugh		silence
$playersounddup	TotenkopfPlayer	male	*puzzfail		*usefail
$playersound	TotenkopfPlayer	male	*falling		bjfall // Sound by CGEffex

Totenkopf/getweapon  "Sounds/Totenkopf/totenkopf_getweapon.ogg"
Totenkopf/atkknife "Sounds/Totenkopf/totenkopf_atkknife.ogg"
Totenkopf/hitenemy "Sounds/Totenkopf/totenkopf_hitenemy.ogg"
Totenkopf/atkpistol "Sounds/Totenkopf/totenkopf_atkpistol.ogg"
Totenkopf/atkkar98 "Sounds/Totenkopf/totenkopf_atkkar98.ogg"
Totenkopf/kar98bolt "Sounds/Totenkopf/totenkopf_kar98bolt.ogg"
Totenkopf/atkmp40 "Sounds/Totenkopf/totenkopf_atkmp40.ogg"
Totenkopf/atkstg44 "Sounds/Totenkopf/totenkopf_atkstg44.ogg"
Totenkopf/flamethrower "Sounds/Totenkopf/totenkopf_flamethrower.ogg"
Totenkopf/missilefire "Sounds/Totenkopf/totenkopf_missilefire.ogg"
Totenkopf/missilehit "Sounds/Totenkopf/totenkopf_missilehit.ogg"
Totenkopf/atkchaingun "Sounds/Totenkopf/totenkopf_atkchaingun.ogg"
Totenkopf/atkflakgun "Sounds/Totenkopf/totenkopf_atkflakgun.ogg"
Totenkopf/atkmauser "Sounds/Totenkopf/totenkopf_atkmauser.ogg"
Totenkopf/atkmg42 "Sounds/Totenkopf/totenkopf_atkmg42.ogg"
Totenkopf/Bonus "Sounds/Totenkopf/totenkopf_bonus1up.ogg"
Totenkopf/Death "Sounds/Totenkopf/totenkopf_playerdeath.ogg"

$random Totenkopf/Hitflesh { Totenkopf/Hitflesh1 Totenkopf/Hitflesh2 Totenkopf/Hitflesh3 }
Totenkopf/Hitflesh1 "Sounds/Totenkopf/totenkopf_hitflesh1.ogg"
Totenkopf/Hitflesh2 "Sounds/Totenkopf/totenkopf_hitflesh2.ogg"
Totenkopf/Hitflesh3 "Sounds/Totenkopf/totenkopf_hitflesh3.ogg"

$limit Totenkopf/MissileHit 128
$limit Totenkopf/Ricochet 128
$random Totenkopf/Ricochet { Totenkopf/Ricochet1 Totenkopf/Ricochet2 Totenkopf/Ricochet3 }
Totenkopf/Ricochet1 "Sounds/Totenkopf/totenkopf_ricochet1.ogg"
Totenkopf/Ricochet2 "Sounds/Totenkopf/totenkopf_ricochet2.ogg"
Totenkopf/Ricochet3 "Sounds/Totenkopf/totenkopf_ricochet3.ogg"

$limit Totenkopf/Explosion 128
$random Totenkopf/Explosion { Totenkopf/Explosion1 Totenkopf/Explosion2 Totenkopf/Explosion3 }
Totenkopf/Explosion1 "Sounds/Totenkopf/totenkopf_explosion1.ogg"
Totenkopf/Explosion2 "Sounds/Totenkopf/totenkopf_explosion2.ogg"
Totenkopf/Explosion3 "Sounds/Totenkopf/totenkopf_explosion3.ogg"

Totenkopf/slurpie "Sounds/Totenkopf/totenkopf_slurpie.ogg"

