Goldfinger/Reload "Sounds/Goldfinger/goldfinger_reload.wav"
Goldfinger/DryFire "Sounds/Goldfinger/goldfinger_dryfire.wav"
Goldfinger/DB5/Move "Sounds/Goldfinger/goldfinger_drive.wav"

Goldfinger/ColtShot "Sounds/Goldfinger/goldfinger_coltshot.wav"
Goldfinger/P08Shot "Sounds/Goldfinger/goldfinger_p08shot.wav"
Goldfinger/P38Shot "Sounds/Goldfinger/goldfinger_p38shot.wav"
Goldfinger/AK47Shot "Sounds/Goldfinger/goldfinger_ak47shot.wav"
Goldfinger/MP40Shot "Sounds/Goldfinger/goldfinger_mp40shot.wav"
Goldfinger/ThompsonShot "Sounds/Goldfinger/goldfinger_thompsonshot.wav"
Goldfinger/M14Shot "Sounds/Goldfinger/goldfinger_m14shot.wav"
Goldfinger/ShotgunShot "Sounds/Goldfinger/goldfinger_shotgunshot.wav"
Goldfinger/PurdeyShot "Sounds/Goldfinger/goldfinger_purdeyshot.wav"
Goldfinger/GarandShot "Sounds/Goldfinger/goldfinger_garandshot.wav"
Goldfinger/CarbineShot "Sounds/Goldfinger/goldfinger_carbineshot.wav"
Goldfinger/AR7Shot "Sounds/Goldfinger/goldfinger_ar7shot.wav"
Goldfinger/MagnumShot "Sounds/Goldfinger/goldfinger_magnumshot.wav"
Goldfinger/GrenadeShot "Sounds/Goldfinger/goldfinger_grenadeshot.wav"
Goldfinger/HatSwitch "Sounds/Goldfinger/goldfinger_hatswitch.wav"
Goldfinger/HatCollide "Sounds/Goldfinger/goldfinger_hatcollide.wav"
$random Goldfinger/HatThrow { Goldfinger/HatThrow1 Goldfinger/HatThrow2 Goldfinger/HatThrow3 }
Goldfinger/HatThrow1 "Sounds/Goldfinger/goldfinger_hatthrow1.wav"
Goldfinger/HatThrow2 "Sounds/Goldfinger/goldfinger_hatthrow2.wav"
Goldfinger/HatThrow3 "Sounds/Goldfinger/goldfinger_hatthrow3.wav"