#library "BLAKE"
#include "zcommon.acs"

Script 459 (void)
{
		if(CheckWeapon("Auto Charge Pistol"))
		{
			SetResultValue(1);
			SetHudSize(320,240,0);
			HudMessage(s:"You can not use this item with this weapon"; 0, 578, CR_LIGHTBLUE, 160.0, 200.0, 1.0);
		}
		else
		if (CheckWeapon("Slow Fire Protector") || CheckWeapon("Heavy Assault Weapon"))
		{
			if(CheckInventory("Shell") == GetAmmoCapacity("Shell"))
			{
				SetHudSize(320,240,0);
				HudMessage(s:"You have maximum ammo on this weapon"; 0, 578, CR_LIGHTBLUE, 160.0, 200.0, 1.0);			
				SetResultValue(1);
			}
			else
				SetResultValue(0);
		}
		else
		if (CheckWeapon("Rapid Assault Weapon"))
		{
			if(CheckInventory("Clip") == GetAmmoCapacity("Clip"))
			{
				SetHudSize(320,240,0);
				HudMessage(s:"You have maximum ammo on this weapon"; 0, 578, CR_LIGHTBLUE, 160.0, 200.0, 1.0);
				SetResultValue(1);
			}
			else	
				SetResultValue(0);
		}
		else
		if (CheckWeapon("Plasma Discharge Unit"))
		{
			if(CheckInventory("RocketAmmo") == GetAmmoCapacity("RocketAmmo"))
			{
				SetHudSize(320,240,0);
				HudMessage(s:"You have maximum ammo on this weapon"; 0, 578, CR_LIGHTBLUE, 160.0, 200.0, 1.0);
				SetResultValue(1);
			}
			else		
				SetResultValue(0);
		}
		else
		if (CheckWeapon("Dual Neutron Disruptor") || CheckWeapon("Anti-Plasma Cannon"))
		{	
			if(CheckInventory("Cell") == GetAmmoCapacity("Cell"))
			{
				SetHudSize(320,240,0);
				HudMessage(s:"You have maximum ammo on this weapon"; 0, 578, CR_LIGHTBLUE, 160.0, 200.0, 1.0);
				SetResultValue(1);
			}
			else		
				SetResultValue(0);
		}
}

Script 460 (void)
{
		if (CheckWeapon("Slow Fire Protector") || CheckWeapon("Heavy Assault Rifle"))
		{
			if(CheckInventory("Shell") <= GetAmmoCapacity("Shell"))
				GiveInventory("Shell", (GetAmmoCapacity("Shell")/4));
		}
		if (CheckWeapon("Rapid Assault Rifle"))
		{
			if(CheckInventory("Clip") <= GetAmmoCapacity("Clip"))
				GiveInventory("Clip", (GetAmmoCapacity("Clip")/4));
		}
		if (CheckWeapon("Plasma Discharge Unit"))
		{
			if(CheckInventory("RocketAmmo") <= GetAmmoCapacity("RocketAmmo"))
				GiveInventory("RocketAmmo", (GetAmmoCapacity("RocketAmmo")/4));
		}
		if (CheckWeapon("Dual Neutron Disruptor") || CheckWeapon("Anti-Plasma Cannon"))
		{	
			if(CheckInventory("Cell") <= GetAmmoCapacity("Cell"))
				GiveInventory("Cell", (GetAmmoCapacity("Cell")/4));
		}
}