Script "DN64PlasmaDeath" (void)
{
	SetActorProperty(0, APROP_RenderStyle, STYLE_TranslucentStencil); Delay(3);
	SetActorProperty(0, APROP_Alpha, 0.8); Delay(5);
	SetActorProperty(0, APROP_Alpha, 0.6); Delay(5);
	SetActorProperty(0, APROP_Alpha, 0.8); Delay(4);
	SetActorProperty(0, APROP_Alpha, 1.0); Delay(5);
	SetActorProperty(0, APROP_Alpha, 0.8); Delay(5);
	SetActorProperty(0, APROP_Alpha, 0.6); Delay(3);
}