Script "DarkForces_GiveShield" ENTER
{
	if(PlayerClass(PlayerNumber()) == 15) // Check if player is playing as Kyle Katarn
	{
		if (CheckInventory("KatarnShieldHasBeenGiven") == 1) // Check if shield has been given before
		{
			terminate; // Terminate script if shield has been given before
		}
		
		if ((IsSinglePlayer() || IsCoop())) // Check if game is singleplayer or coop
		{
			GiveInventory("KatarnStarterShield",1);
			GiveInventory("KatarnShieldHasBeenGiven",1);
		}
	}
	terminate;
}	