Script "DisruptorPlasmaLanceAngle" (void)
{
	SetActivatorToTarget(0);
	SetResultValue(CheckInventory("PlasmaLanceAngle"));
}

Script "DisruptorPlasmaLancePitch" (void)
{
	SetActivatorToTarget(0);
	SetResultValue(GetActorPitch(0));
}

Script "DisruptorPSICooldown" (void)
{
    if (CheckInventory("DisruptorPSICooldown") > 0)
    {
        delay(35);
        TakeInventory("DisruptorPSICooldown",1);
        restart;
    }
}