//======================================================================================================================
//									Any changes to a file prefixed "CLASS", compile this
//======================================================================================================================

#library "Class"
#include "zcommon.acs"
#include "commonFuncs.acs"

#include "ClassROTT.acs"
#include "ClassHalfLife.acs"
#include "ClassHexen2.acs"
#include "ClassGoldeneye.acs"