Script "DarkForces_GiveShield" (void)
{
	if (CheckInventory("KatarnShieldHasBeenGiven") == 1) // Check if shield has been given before
	{
		terminate; // Terminate script if shield has been given before
	}

	if ((IsSinglePlayer() || IsCoop())) // Check if game is singleplayer or coop
	{
		GiveInventory("KatarnStarterShield",1);
		
		if (isSinglePlayer()) // Check if game is on singleplayer again
		{
			GiveInventory("KatarnShieldHasBeenGiven",1);
		}
	}
	terminate;
}	