int ClassPickupSounds[CLASSCOUNT][MAXMODES][SLOTCOUNT] = 
{
    {
		{
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
		},
		{
			"doom64guy/weaponget",
			"doom64guy/weaponget",
			"doom64guy/weaponget",
			"doom64guy/weaponget",
			"doom64guy/weaponget",
			"doom64guy/weaponget",
			"doom64guy/weaponget",
			"doom64guy/weaponget",
			"doom64guy/weaponget",
			"doom64guy/weaponget",
		}
    },
    {{
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
    }},
    {{
        "heretic/weaponget",
        "heretic/weaponget",
        "heretic/weaponget",
        "heretic/weaponget",
        "heretic/weaponget",
        "heretic/weaponget",
        "heretic/weaponget",
        "heretic/weaponget",
        "heretic/weaponget",
        "heretic/weaponget",
    }},
    {
		{
			"wolfen/knifeget",
			"wolfen/knifeget",
			"wolfen/itemget",
			"wolfen/mgunget",
			"wolfen/mgunget",
			"wolfen/weaponget",
			"wolfen/rocketget",
			"wolfen/flameget",
			"wolfen/spearget",
			"wolfen/knifeget",
		},
		{
			"wolfen/knifeget",
			"wolfen/knifeget",
			"wolfen/itemget",
			"wolfen/mgunget",
			"wolfen/mgunget",
			"wolfen/weaponget",
			"wolfen/rocketget",
			"wolfen/flameget",
			"wolfen/spearget",
			"wolfen/knifeget",
		},
		{
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
		}
    },
    {
		{
			"hexen/artiget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/artiget",
		},
		{
			"hexen/artiget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/artiget",
		},
		{
			"hexen/artiget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/weaponget",
			"hexen/artiget",
				
    }},
    {
		{
			"duke/weaponget",
			"duke/itemget",
			"duke/weaponget",
			"duke/mosspump2",
			"duke/xshotgunpump",
			"duke/weaponget",
			"duke/weaponget",
			"duke/weaponget",
			"duke/weaponget",
			"duke/itemget",
		},
		{
			"duke/woohoo",
			"duke/itemget",
			"duke/woohoo",
			"duke/mosspump2",
			"duke/xshotgunpump",
			"duke/woohoo",
			"duke/woohoo",
			"duke/woohoo",
			"duke/woohoo",
			"duke/itemget",
		},
	},
    {{
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/bigitemget",
        "marathon/itemget",
    }},
    {{
        "quakeweps/weaponget",
        "quakeweps/weaponget",
        "quakeweps/weaponget",
        "quakeweps/weaponget",
        "quakeweps/weaponget",
        "quakeweps/weaponget",
        "quakeweps/weaponget",
        "quakeweps/weaponget",
        "quakeweps/quadget",
        "quakeweps/weaponget",
    }},
	{
		{
			"gen/pickup",	
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/bpicku",
		},
		{
			"gen/pickup",	
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/bpicku",
		},
		{
			"gen/pickup",	
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/bpicku",
		},
		{
			"gen/pickup",	
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/pickup",
			"gen/bpicku",
		},
	},
	{
		{	// Blake sounds - Added this.
			"",
			"Bstone/ammoget",
			"Bstone/wep1get",
			"Bstone/wep2get",
			"Bstone/wep3get",
			"Bstone/wep3get",
			"Bstone/wep4get",
			"Bstone/wep5get",
			"Bstone/wep4get",
		},
		{
			"",
			"Bstone/ammoget",
			"Bstone/wep1get",
			"Bstone/wep2get",
			"Bstone/wep3get",
			"Bstone/wep3get",
			"Bstone/wep4get",
			"Bstone/wep5get",
			"Bstone/wep4get",
			
	}},
	{{	// Caleb sounds - Added this.
		"Caleb/Weaponup",
		"Caleb/Weaponup",
		"Caleb/Weaponup",
		"Caleb/Weaponup",
		"Caleb/Weaponup",
		"Caleb/Weaponup",
		"Caleb/Weaponup",
		"Caleb/Weaponup",
		"Caleb/Weaponup",
	}},
    {{	//Strifeguy sounds - Added this.
        "strife/weaponget", // Fist
        "strife/itemget", // Chainsaw
        "strife/weaponget", // Pistol
        "strife/weaponget", // Shotgun
        "strife/weaponget", // Super Shotgun
        "strife/weaponget", // Chaingun
        "strife/weaponget", // Rocket Launcher
        "strife/weaponget", // Plasma Rifle
        "strife/weaponget", // BFG9000
        "strife/itemget", // Punchdrunk Chainsaw
    }},	
    {{	//Eleena sounds - Added this.
        "EradAmmo/PUP", // Fist
        "EradAmmo/PUP", // Chainsaw
        "EradAmmo/PUP", // Pistol
        "EradAmmo/PUP", // Shotgun
        "EradAmmo/PUP", // Super Shotgun
        "EradAmmo/PUP", // Chaingun
        "EradAmmo/PUP", // Rocket Launcher
        "EradAmmo/PUP", // Plasma Rifle
        "EradAmmo/UPUP", // BFG9000
		"",
    }},	
    {{ // C7 Sounds
		"C7/AmmoPickup",
		"C7/AmmoPickup",
		"C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
    }},
    {{ // RMR Sounds
		"RMR/pickup",
		"RMR/pickup",
		"RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
    }},			
    {{
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
    }},	
	{{
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/megapick",
		"greed/pickup",
	}},	
    {{
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
    }},		
	{{
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gtwo/megapickup",
		"gpickup/gen",
	}},
	{
		{
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/egon_pickup",
			"halflife/weaponpickup",
		},
		{
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/egon_pickup",
			"halflife/weaponpickup",
		},
	},	
	{{ // Lo Wang
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickupbig",
    }},	
	{{ 
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
    }},
	{{ // Jon
        "PS/Wpickup",
        "PS/Wpickup",
        "PS/Wpickup",
        "PS/Wpickup",
        "PS/Wpickup",
        "PS/Wpickup",
        "PS/Wpickup",
        "PS/Wpickup",
        "PS/Wpickup",
    }},
	{{ // Leonard
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
    }},	
	{{
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
    }},
	{{
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
    }},
	{{
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
    }},
/*	{
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
    },	*/
};

int ClassDropSounds[CLASSCOUNT][MAXMODES][SLOTCOUNT] = 
{
    {
		{
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
			"doomguy/weaponget",
		},
		{
			"doom64guy/itemget",
			"doom64guy/itemget",
			"doom64guy/itemget",
			"doom64guy/itemget",
			"doom64guy/itemget",
			"doom64guy/itemget",
			"doom64guy/itemget",
			"doom64guy/itemget",
			"doom64guy/itemget",
			"doom64guy/itemget",
		},
	},
    {{
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
        "chex/weaponget",
    }},
    {{
        "heretic/ammoget",
        "heretic/ammoget",
        "heretic/ammoget",
        "heretic/ammoget",
        "heretic/ammoget",
        "heretic/ammoget",
        "heretic/ammoget",
        "heretic/ammoget",
        "heretic/ammoget",
        "heretic/ammoget",
    }},
    {
		{
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
		},
		{
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
			"wolfen/itemget",
		},
		{
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
			"Totenkopf/getweapon",
		}
	},
    {{
        "hexen/itemget",
        "hexen/itemget",
        "hexen/itemget",
        "hexen/itemget",
        "hexen/itemget",
        "hexen/itemget",
        "hexen/itemget",
        "hexen/itemget",
        "hexen/itemget",
        "hexen/itemget",
    }},
    {
		{
			"duke/itemget",
			"duke/itemget",
			"duke/itemget",
			"duke/itemget",
			"duke/itemget",
			"duke/itemget",
			"duke/itemget",
			"duke/itemget",
			"duke/itemget",
			"duke/itemget",
		},
		{
			"duke/woohoo",
			"duke/itemget",
			"duke/woohoo",
			"duke/itemget",
			"duke/itemget",
			"duke/woohoo",
			"duke/woohoo",
			"duke/woohoo",
			"duke/woohoo",
			"duke/itemget",
		},
	},
    {{
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/itemget",
        "marathon/bigitemget",
        "marathon/itemget",
    }},
    {{
        "quakeweps/itemget",
        "quakeweps/itemget",
        "quakeweps/itemget",
        "quakeweps/itemget",
        "quakeweps/itemget",
        "quakeweps/itemget",
        "quakeweps/itemget",
        "quakeweps/itemget",
        "quakeweps/quadget",
        "quakeweps/itemget",
    }},
	{{	// Rott pickup sounds - Added this.
        "gen/pickup",
        "gen/pickup",
        "gen/pickup",
        "gen/pickup",
        "gen/pickup",
        "gen/pickup",
        "gen/pickup",
        "gen/pickup",
        "gen/bpicku",
    }},
	{
		{	// Blake pickup sounds - Added this.
			"",
			"Bstone/ammoget",
			"Bstone/wep1get",
			"Bstone/wep2get",
			"Bstone/wep3get",
			"Bstone/wep3get",
			"Bstone/wep4get",
			"Bstone/wep5get",
			"Bstone/wep4get",
		},
		{
			"",
			"Bstone/ammoget",
			"Bstone/wep1get",
			"Bstone/wep2get",
			"Bstone/wep3get",
			"Bstone/wep3get",
			"Bstone/wep4get",
			"Bstone/wep5get",
			"Bstone/wep4get",
		
	}},
	{{	// Caleb sounds - Added this.
		"Caleb/Ammo",
		"Caleb/Ammo",
		"Caleb/Ammo",
		"Caleb/Ammo",
		"Caleb/Ammo",
		"Caleb/Ammo",
		"Caleb/Ammo",
		"Caleb/Ammo",
		"Caleb/Ammo",
	}},  
	{{	//Strife
        "strife/ammoget", // Fist
        "strife/itemget", // Chainsaw
        "strife/ammoget", // Pistol
        "strife/ammoget", // Shotgun
        "strife/ammoget", // Super Shotgun
        "strife/ammoget", // Chaingun
        "strife/ammoget", // Rocket Launcher
        "strife/ammoget", // Plasma Rifle
        "strife/ammoget", // BFG9000
        "strife/itemget", // Punchdrunk Chainsaw
    }},
/*    {
        "doom64guy/itemget",
        "doom64guy/itemget",
        "doom64guy/itemget",
        "doom64guy/itemget",
        "doom64guy/itemget",
        "doom64guy/itemget",
        "doom64guy/itemget",
        "doom64guy/itemget",
        "doom64guy/itemget",
        "doom64guy/itemget",
    }, */
    {{	//Eleena sounds - Added this.
        "EradAmmo/PUP", // Fist
        "EradAmmo/PUP", // Chainsaw
        "EradAmmo/PUP", // Pistol
        "EradAmmo/PUP", // Shotgun
        "EradAmmo/PUP", // Super Shotgun
        "EradAmmo/PUP", // Chaingun
        "EradAmmo/PUP", // Rocket Launcher
        "EradAmmo/PUP", // Plasma Rifle
        "EradAmmo/UPUP", // BFG9000
    }},	
    {{ // C7 Sounds
		"C7/AmmoPickup",
		"C7/AmmoPickup",
		"C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
        "C7/AmmoPickup",
    }},		
    {{ // RMR Sounds
		"RMR/pickup",
		"RMR/pickup",
		"RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
        "RMR/pickup",
    }},	
    {{
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
        "katarn/itemup",
    }},	
	{{
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/pickup",
		"greed/megapick",
		"greed/pickup",
	}},	
    {{
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
        "Disruptor/itemup",
    }},			
	{{
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gpickup/gen",
		"gtwo/megapickup",
		"gpickup/gen",
	}},
	{
		{
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/egon_pickup",
			"halflife/weaponpickup",
		},
		{
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/weaponpickup",
			"halflife/egon_pickup",
			"halflife/weaponpickup",
		},
	},	
	//Lo Wang
	{{
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickup",
        "Item/SWpickupbig",
    }},		
	{{ 
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",
        "CM/WeaponUp",		
        "CM/WeaponUp",
    }},
	{{ // Jon
        "PS/Ipickup",
        "PS/Ipickup",
        "PS/Ipickup",
        "PS/Ipickup",
        "PS/Ipickup",
        "PS/Ipickup",
        "PS/Ipickup",
        "PS/Ipickup",
        "PS/Ipickup",
    }},
	{{ // Leonard
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
        "RR/Wpickup",
    }},	
	{{
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
        "Q2Misc/W_Pkup",
    }},
	{{
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
        "Hexen2/WeaponPickup",
    }},
	{{
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
        "Goldeneye/Weaponup",
    }},
/*	{
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
        "Totenkopf/getweapon",
    },	*/
};

int ClassUniqueSounds[CLASSCOUNT][MAXMODES] = 
{
    { "doomguy/itemget", "doom64guy/powerupget", },
    { "chex/weaponget", "" },
    {"heretic/itemget", "" },
    {"wolfen/lifeget", "wolfen/lifeget", "Totenkopf/getweapon" },
    {"hexen/artiget", "hexen/artiget", "hexen/artiget" },
    {"duke/itemget", "duke/itemget" },
    {"marathon/itemget", "" },
    {"quakeweps/weaponget", "" },
	{"excalibat/pick", "" }, // Added this.
	{"Bstone/xylanget", "Bstone/xylanget" }, // Added this.
	{"Caleb/Weaponup2", "" }, // Added this.
    {"strife/itemget", "" }, // For your class	
    {"EradAmmo/UPUP", "" },	
    {"C7MinePlace", "" },
	{"RMR/pickup", "" },
    {"katarn/itemup", "" },	
	{"greed/pickup", "" }, //+Added	
	{"Disruptor/Special", "" }, //+Added	
	{"gpickup/gen", "" }, //+Added
	{"halflife/squeak_pickup", "halflife/squeak_pickup" },	
	{"Item/SWpickup", "" },	
	{"misc/cm_pkup",	 "" },
    {"PS/Ipickup2", "" },
    {"RR/Wpickup", "" },
	{"Q2Misc/W_Pkup", "" },
	{"Hexen2/ArtifactPickup", "" },
	{"Goldeneye/Weaponup", "" },
//	"Totenkopf/getweapon"	
};

int PunchDrunkUniqueSounds[CLASSCOUNT] = 
{
    "doomguy/itemget",
    "chex/weaponget",
    "heretic/itemget",
    "wolfen/lifeget",
    "hexen/weaponget",
    "duke/itemget",
    "marathon/itemget",
    "quakeweps/weaponget",
	"",
    "",
    "",
    "strife/itemget",
//    "doom64guy/powerupget",
	"",
    "C7/AmmoPickup",
	"",
    "katarn/itemup",
	"greed/pickup", //+Added	
	"",	
	"gpickup/gen", //+Added
	"halflife/squeak_pickup",	
	"",	
	"",
	"",	
	"",
	"Q2Misc/W_Pkup",
	"Goldeneye/Weaponup",
//	"Totenkopf/getweapon"	
};
