int KilledOracle = 0;
int AwakenSpectres = 0;
int SpectreTarget;

#define ACCURACYCOUNT   10
#define SIGILCOUNT      5

int SigilSplinters[SIGILCOUNT] = 
{
    "SigilSplinter1",
    "SigilSplinter2",
    "SigilSplinter3",
    "SigilSplinter4",
    "SigilSplinter5",
};

int SpectralTogglers[SIGILCOUNT] = 
{
    "SigilInventoryWeapon1",
    "SigilInventoryWeapon2",
    "SigilInventoryWeapon3",
    "SigilInventoryWeapon4",
    "SigilInventoryWeapon5",
};

int BeaconMonsters[CLASSCOUNT] = 
{
    "FriendlyDoomImp",
    "FriendlyFlemoid",
    "FriendlyNitrogolem",
    "FriendlyNazi",
    "FriendlyAfrit",
    "FriendlyAlienTrooper",
    "FriendlyPfhorTrooper",
    "FriendlyGrunt",
	"FriendlyLowGuard",
    "FriendlySectorPatrol",
    "FriendlyBrownCultist",
	"FriendlySuperRebelSpawner",		
//    "FriendlyDoomImp64",
    "FriendlyHSD",
    "FriendlyAnimatedProbe",	
    "FriendlyUNBluesuit",	
    "FriendlyStarTrooper",	
	"FriendlyRobotGuard", //+Added
    "FriendlyTerroristDroid", //+Added
	"FriendlyMinoDrake", //+Added
	"FriendlyBarney", //+Added
	"FriendlyFatAss", //+Added
	"FriendlyCMTrooper", //+Added
	"FriendlyAnubisWarrior", //+Added
	"FriendlyTurdMinion", //+Added
	"FriendlyRobotGuard", //+Added
};

int AccuracyUniques[CLASSCOUNT][ACCURACYCOUNT] = 
{
    {"DoomZerkCounter",  "", "", "", "", "", "", "", "", ""},
    {"ChexSoulsphere",   "", "", "", "", "", "", "", "", ""},
    {"ArtiEgg2",         "", "", "", "", "", "", "", "", ""},
    {"WolfStrifeUnique1",    "Totenkopf_FlameThrowerFuel", "WolfStrifeUnique2", "Cell", "WolfStrifeUnique3", "Shell", "", "", "", ""},
    {"PortMysticAmbit",  "", "", "", "", "", "", "", "", ""},
    {"DukeguyStrifeJet", "", "", "", "", "", "", "", "", ""},
    {"RandAlienWeapon",  "", "", "", "", "", "", "", "", ""},
    {"Laser Cannon",     "RangerMaxCells", "", "", "", "", "", "", "", ""},
	{"Excalibat",      "BMissiles", "Dark Staff", "DSEnergy", "Split Missile", "SMissiles", "", "", "", ""},
    {"BlakeShield",      "", "", "", "", "", "", "", "", ""},
    {"VoodooDoll",      "Voodoo", "Guns Akimbo", "", "Spraycan", "SpraycanAmmo", "", "", "", ""},
    {"Upgrades",         "", "", "", "", "", "", "", "", ""},
//    {"Doom64GuyZerkCounter",    "", "", "", "", "", "", "", "", ""},
    {" Eradicator Enhancement Chip ",      "", "", "", "", "", "", "", "", ""},
    {"C7ProxyMinePickup",      "C7ProxyMineAmmo", "", "", "", "", "", "", "", ""},
    {"RMROxygenRecycler","", "", "", "", "", "", "", "", ""},
    {"KatarnFireRateUp", "", "", "", "", "", "", "", "", ""},
	{"IPOGRandomItemGenerator","","","","","","","","",""}, //+Added	
	{"DisruptorEnergyBall","","","","","","","","",""}, //+Added
	{"WTShieldTrigger","","","","","","","","",""}, //+Added
	{"HL Squeaks","HLSqueakAmmo","HL Crossbow","Shell","HL Squeaks","RocketAmmo","","","",""},
	{"SWRipperHeart","HeartAmmo","HeatSeekingCard","","","","","","",""},		
	{"RandomMagicItem","","","","","","","","",""},
	{"Ring of RA","","","","","","","","",""},	
	{" Hunting Rifle With Scope ","Clip"," Dyn 'O' Mites ","RocketAmmo","","","","","",""},	
	{"Q2GrenadeLauncher","RocketAmmo","Q2ETFRifle","Q2Flechettes","Q2IonRipper","Cell","",""},	
	{"Hexen2TomeOfPower","","Hexen2ForceCube","","","","","","",""},	
	{"Goldeneye_SniperRifle","Goldeneye_SniperDualToken","Goldeneye_SilencedD5K","Goldeneye_D5KDualToken","Goldeneye_GadgetGranter","","",""},
//	{"Totenkopf_FlameThrower","Totenkopf_FlameThrowerFuel","Totenkopf_MG42","Cell","Totenkopf_SniperPickup","Shell","",""},		
};

int DoomAccuracyZerks[ACCURACYCOUNT] = 
{
    "DoomguyStrifeZerk1",
    "DoomguyStrifeZerk2",
    "DoomguyStrifeZerk3",
    "DoomguyStrifeZerk4",
    "DoomguyStrifeZerk5",
    "DoomguyStrifeZerk6",
    "DoomguyStrifeZerk7",
    "DoomguyStrifeZerk8",
    "DoomguyStrifeZerk9",
    "DoomguyStrifeZerk0",
};

int AccuracyMessages[CLASSCOUNT][MSGCOUNT] = 
{
    {
        "You grow more berserk.",
        "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
        "You're not actually getting angrier. You're just punching more accurately.",
        "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
        "It was a ruse! You were secretly in a boxing match all along!",
        "Yes... channel your anger...",
        "Don't get too cocky, Mikey.",
        "Well, if you insist on using your fists...",
        "Plot twist: you were Baratus all along.",
        "Someone spiked the punch.",
    },
    {
        "Supercharge breakfast!",
        "OM NOM NOM NOM",
        "Because medikits are for wimps.",
        "Crunchy.",
        "Chex marks the spot!",
        "Is this cannibalism or what?",
        "It's milk you can chew!",
        "Free breakfast with every training!",
        "How generous of him to provide you breakfast, too.",
        "So, uh, where did you get the milk from? The cows are dead.",
    },
    {
        "MORPH OVUM",
        "Parthoris Fried Chicken.",
        "Because nothing's better than turning an Archvile harmless.",
        "I'm calling fowl on this.",
        "Don't eat it.",
        "I'm sure there's hundreds of egg puns you can use.",
        "Omelettes, break some eggs, etc.",
        "",
        "",
        "",
    },
    {
        "You got an extra life!",
        "Maybe now you can go to college.",
        "Maybe one day this won't suck in Zandronum.",
        "One day, the villains will learn how to respawn, too.",
        "Now you can hug a giant metal robot with no repercussions.",
        "Good for the soul, too.",
        "BULLSHIT I HAD AN EXTRA LIFE WHY'D THE CYBERDEMON KILL ME",
        "Go ahead, taunt those Templars.",
        "",
        "",
    },
    {
        "MYSTIC AMBIT INCANT",
        "Heal plz.",
        "Warning: Not for use in deathmatch.",
        "A crowd on demand.",
        "Well, you're a cleric. Gotta have a heal.",
        "Plot twist: it's a badly-inscribed poison spell.",
        "This would probably be more useful if Strife could do coop.",
        "The rebels already have a doctor...",
        "",
        "",
    },
    {
        "JETPACK!",
        "I believe I can touch the sky.",
        "Guaranteed to make friends with mappers.",
        "And this is why Virus will never be in.",
        "Because you have that on your sprite for a reason.",
        "Watch your ass, the jet burns.",
        "The gas mileage is \caterrible\c-.",
        "And fuck you too, fall damage.",
        "",
        "",
    },
    {
        "You got th@nS0-.'\casystem error \cd0xfded",
        "The difference between a room of aliens and a carpet of them.",
        "What fun to watch you work.",
        "~text interface term\cinal malfunction error \cd~2992dud",
        "your former self destroyed the dreaming way is eased",
        "down to the crushing center and spared the dance of forever",
        "This will allow you to kill more aliens. Does that make you happy?",
        "shedding all the weight of imagined moments and fear",
        "because fear is not the blood",
        "I know who you are.",
    },
    {
        "You got the laser cannon!",
        "If this were in vanilla Quake, it would be slot 6. \ckbut alas",
        "Are any of the weapon designs in Quake even practical?",
        "Do not aim at face. Not that it'll help.",
        "Does it come in blueberry?",
        "What is this, Star Wars?",
        "Bouncy red death!",
        "Pewpewlasers!",
        "Ia ia fhtagn, you flying squash.",
        "Ia ia fhtagn, you floating flower pot.",
    },
	{
        "You've found the mighty Excalibat! or maybe You've wield the Dark Staff!",
        "Baseball time!",
        "Here catch!",
        "I'm off to a field run.",
        "Woah, this bat is as old as El Oscuro!",
        "They'll have a heckuva year if their chest holds out!",
        "",
        "",
        "",
        "",
    },
    {
        "You picked up a Xylan Shield!",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },
    {
        "Picked up the Gambit's Essence.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },	
    {
        "Training Complete!",
        "Why am I doing this?",
        "Bonus level complete!",
        "Mmm... Steroids.",
        "",
        "",
        "",
        "",
        "",
        "",
    },		
/*    {
        "You grow more berserk.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },*/
    {
        "You found a Weapon Enhancement Chip!",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
	},
    {
        "You got a box of Proximity Mines!",
        "I've lost a bomb! Do you have it?",
        "I like to sit on my pancakes. *boom*",
        "Warning: Improper use of explosives will lead to a missing thigh.",
        "Time to be a dick to everyone involved.",
        "Boom time!",
        "",
        "",
        "",
        "",
    },	
    {
        "Oxygen Recycler or Jet Pack!",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },	
    {
        "Weapon Super Charge!",
        "Lock and load! Lock and load your guns!",
        "Oooh, here comes the fire rate!",
        "I'm the man! I'm supercharged!",
        "Yes, a small item makes your guns shoot twice as fast without overheating, because reasons.",
        "What is this, Quake?",
        "",
        "",
        "",
        "",
    },	
	{"kek","","","","","","","","",""},	
    {
        "BALLZ",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },		
	//+Added
	{
		"You got the shield!",
		"Where are the dragons?",
		"(This is just another generic, lame verdict)",
		"Looks like painted Wood. SCAM!",
		"",
		"",
		"",
		"",
		"",
		"",
	},
	{"lel","","","","","","","","",""},	
	{"MEEP","","","","","","","","",""},		
	{"ASDP","","","","","","","","",""},
	{"MEEP","","","","","","","","",""},		
	{"ASDP","","","","","","","","",""},	
	{"BLAB","","","","","","","","",""},	
};


script "SamsaraStrifeAccuracy" (int which) //313 -- SAMSARA_STRIFEACCURACY
{
    if (which == -1) { which = CheckInventory("StrifeAccuracyCounter"); }
    which = middle(1, which, ACCURACYCOUNT) - 1;

    int pln = PlayerNumber();
    int pclass = samsaraClassNum();
    int unique = "";

    while (unique == "")
    {
        unique = AccuracyUniques[pclass][which];
        which--;
    }

    GiveInventory(unique, 1);

    ACS_NamedExecuteAlways("SamsaraClientAccuracy", 0, GetCVar("compat_silentpickup"),0,0);
}

script "SamsaraClientAccuracy" (int soundmode) clientside //314 -- SAMSARA_CLIENT_ACCURACY
{
    int pln = PlayerNumber(), cpln = ConsolePlayerNumber();
    int pclass = samsaraClassNum();
    int i, j, quoteCount = 0;
    int logMsg;
    
    if (cpln == pln)
    {
        if (GetCVar("sams_cl_moremessages"))
        {
            for (i = 0; i < MSGCOUNT; i++)
            {
                j = AccuracyMessages[pclass][i];
                if (!StrLen(j)) { continue; }
                
                QuoteStorage[quoteCount++] = j;
            }
            
            if (!quoteCount) { logMsg = "Oh bugger there's no messages for this unique."; }
            else { logMsg = QuoteStorage[random(0, quoteCount-1)]; }
        }
        else
        {
            logMsg = AccuracyMessages[pclass][0];
            
            if (!StrLen(logMsg)) { logMsg = "Oh bugger there's no message for this unique."; } 
        }

        if (GetCVar("sams_cl_printpickup")) { Print(s:logMsg); }
        else { Log(s:logMsg); }
    }
    
    if (soundmode == 1) { LocalAmbientSound(ClassUniqueSounds[pclass][SamsaraAlternativeClass], 127); }
    else { ActivatorSound(ClassUniqueSounds[pclass][SamsaraAlternativeClass], 127); }
    
    FadeRange(ClassFades[pclass][0], ClassFades[pclass][1], ClassFades[pclass][2], ClassFades[pclass][3],
    ClassFades[pclass][0], ClassFades[pclass][1], ClassFades[pclass][2], 0.0, itof(ClassFades[pclass][4]) / 35);
}

script "SamsaraBeacon" (int noloop) //315 -- SAMSARA_BEACON
{
    int pln, classnum, monType, monTID, success = 0;
    int beaconTID = defaultTID(0);
    int x = GetActorX(0), y = GetActorY(0), z = GetActorZ(0);

    SetActivatorToTarget(0);
    
    pln = PlayerNumber();
    classnum = samsaraClassNum();

    if (pln == -1)
    {
        SetActorState(beaconTID, "WhatAmIDoingWithMyLife");
        terminate;
    }

    monType = BeaconMonsters[classnum];

    SetActivator(beaconTID);

    while (!success)
    {
        monTID = unusedTID(14000, 24000);
        success = Spawn(monType, x, y, z, monTID);
        if (success) { SetPointerExt(AAPTR_Master,0,monTID); Spawn("StrifeTeleportFog", x, y, z); }

        if (noloop)
        {
            SetResultValue(success);

            if (!success) { SetActorState(beaconTID, "FuckYouImAPickup"); }
            terminate;
        }

        Delay(1);
    }
}

script "SamsaraSpectres" (int mode, int arg1, int arg2) //316 -- SAMSARA_SPECTRES
{
    int i,j,k,l, x,y,z;
    int result;

    switch (mode)
    {
      default:
        x = GetActorX(0);
        y = GetActorY(0);
        z = GetActorZ(0);

        for (i = 0; i < 50; i++)
        {
            j = unusedTID(5000, 10000);
            Spawn("AmmoSatchel", x,y,z, j);
            k = random(0, 1.0);
            l = random(0, 1.0);

            SetActorVelocity(j, 35 * FixedMul(cos(k), cos(l)), 35 * FixedMul(sin(k), cos(l)), 35 * sin(l), 0, 0);

            if (i % 4 == 0) { Delay(1); }
        }
        break;

      case 1:
        SamsaraGlobal[GLOBAL_SIGILBASE+1] = 1;
        Floor_LowerToLowest(999, 4);
        SetActivatorToTarget(0);
        GiveInventory("Communicator", 1);
        SendToCommunicator(95, 0, 0, 0);
        break;

      case 2:
        SamsaraGlobal[GLOBAL_SIGILBASE+2] = 1;
        SetActivatorToTarget(0);
        Print(l:"TXT_KILLED_BISHOP");
        GiveInventory("Communicator", 1);
        GiveInventory("QuestItem21", 1);
        SendToCommunicator(74, 0, 0, 0);
        break;

      case 3:
        SamsaraGlobal[GLOBAL_SIGILBASE+3] = 1;
        Door_Open(222, 8);
        KilledOracle = 1;        
        SetActivatorToTarget(0);
        GiveInventory("Communicator", 1);
        Print(l:"TXT_KILLED_ORACLE");
        GiveInventory("QuestItem23", 1);

        if (CheckInventory("QuestItem21")) { GiveInventory("QuestItem22", 1); }

        if (CheckInventory("QuestItem24")) { SendToCommunicator(85, 0, 0, 0); }
        else { SendToCommunicator(87, 0, 0, 0); }

        Delay(35);

        KilledOracle = 0;
        break;

      case 4:
        SamsaraGlobal[GLOBAL_SIGILBASE+4] = 1;
        SetActivatorToTarget(0);
        Print(l:"TXT_KILLED_MACIL");
        GiveInventory("Communicator", 1);
        GiveInventory("QuestItem24", 1);

        if (CheckInventory("QuestItem25")) { SendToCommunicator(106, 0, 0, 0); }
        else { SendToCommunicator(79, 0, 0, 0); }
        break;

      case 5:
        SamsaraGlobal[GLOBAL_SIGILBASE+5] = 1;
        Floor_LowerToLowest(666, 4);
        SetActivatorToTarget(0);

        Print(l:"TXT_KILLED_LOREMASTER");
        GiveInventory("Communicator", 1);
        GiveInventory("QuestItem26", 1);

        ACS_NamedExecuteAlways("SamsaraStrifeAccuracy", 0, -1,0,0);
        GiveInventory("UpgradeStamina", 1);

        if (CheckInventory("QuestItem23") && CheckInventory("QuestItem24") && CheckInventory("QuestItem21"))
        {
            SendToCommunicator(85, 0, 0, 0);
        }
        else
        {
            SendToCommunicator(83, 0, 0, 0);
        }
        break;

      case 6:
        if (arg1 < 1 || arg1 > SIGILCOUNT)
        {
            Log(s:"\caERROR\c-: Illegal value for sigil splinter given to script ", s:"SamsaraSpectres", s:" (", d:arg1, s:")");
            break;
        }

        SamsaraGlobal[GLOBAL_SIGILBASE + arg1] = !!arg2;
        break;

      case -1:
        SetActivatorToTarget(0);
        i = defaultTID(-1);

        AwakenSpectres = 1;
        SpectreTarget = i;

        Delay(35);
        AwakenSpectres = 0;
        SpectreTarget = 0;
        break;

      case -2:
        if (AwakenSpectres)
        {
            Thing_Hate(0, SpectreTarget, 0);
            SetActorState(0, "See");
        }
        break;
        
      case -3:
        result = KilledOracle;
        break;
    }

    SetResultValue(result);
}

script "SamsaraSigil" (int sequence) //317 -- SAMSARA_SIGIL
{
	int i, splinterCount = 0;
	switch(sequence)
	{
		case 1:
			Delay(21);
			GiveInventory("SigilInventorySequence1",1);
			for (i = 0; i < SIGILCOUNT; i++)
			{
				if (CheckInventory(SigilSplinters[i])) { splinterCount++; }
			}
			DamageThing(2 * splinterCount, 0);
			break;
		case 2:
			Delay(4);
			GiveInventory("SigilInventorySequence2",1);
			break;
		case 3:
			Delay(6);
			GiveInventory("SigilInventorySequence3",1);
			break;
		case 4:
			Delay(4);
			GiveInventory("SigilInventorySequence4",1);
			break;
	}
}
