script "SamsaraZScript" (int arg)
{	
	// Check if Samsara is running on a ZScript-compatible source port
    if(GetCvar("samsara_zscriptready") == 1)
    {
        switch (arg)
        {
          // Handle Bolognese wall blood decals (This is unfinished, so I'll have to find a way to get the TIDs from the monster later)
		  case 0:
			//SpawnSpotFacingForced("Bolognese_WallBlood_ZScript", 0, 0);
            break;
        }
    }
}
