#define WEPFLAGS_GOTWEAPON  1
#define WEPFLAGS_WEAPONSTAY 2

#define CHOICECOUNT         5
#define CHOICECOUNT_U       (UNIQUECOUNT*2)

#define S_WEP               0
#define S_AMMO1             1
#define S_AMMO2             2
#define S_CHECKITEM         3
#define S_CHECKFAILITEM     4

#define U_UNIQUE1           0
#define U_AMMO1             1
#define U_UNIQUE2           2
#define U_AMMO2             3
#define U_UNIQUE3           4
#define U_AMMO3             5

#define SLOT_UNIQUE        -1
#define SLOT_FIST           0
#define SLOT_CHAINSAW       1
#define SLOT_PISTOL         2
#define SLOT_SHOTGUN        3
#define SLOT_SUPERSHOTGUN   4
#define SLOT_SSG            4
#define SLOT_CHAINGUN       5
#define SLOT_ROCKETLAUNCHER 6
#define SLOT_PLASMARIFLE    7
#define SLOT_BFG9000        8
#define SLOT_BFG            8

int ClassUniques[CLASSCOUNT][CHOICECOUNT_U] =
{
    {"DoomguyBerserker",              "",                         "",                      "",                      "",                        ""},
    {"ChexSoulsphere",                "",                         "",                      "",                      "",                        ""},
    {"PortTomeCoop",                  "",                         "Grim Ballista",         "Shell",                 "SamsaraCorvusArtiEgg",    ""},
    {"WolfExtraLife",                 "",                         "",                      "",                      "",                        ""},
    {"PortMysticAmbit",               "",                         "",                      "",                      "",                        ""},
    {"DukePortJetpack",               "DukeJetpackFuel",          "Shrinker",              "ShrinkerAmmo",          "Expander",                "ExpanderAmmo"},
    {"Alien Weapon",                  "UnknownAmmo",              " Alien Weapon ",        "UnknownAmmo2",          "",                        ""},
    {"Laser Cannon",                  "Cell",                     "",                      "",                      "",                        ""},
    {"Excalibat",                     "BMissiles",                "Split Missile",         "SMissiles",             "Dark Staff",              "DSEnergy"},
    {"BlakeRefill",                   "",                         "",                      "",                      "",                        ""},
    {"VoodooDoll",                    "Voodoo",                   "Guns Akimbo",           "",                      "Spraycan",                "SprayCanAmmo"},
    {"Upgrades",                      "",                         "",                      "",                      "",                        ""},
    //{"Doom64GuyBerserk",              "",                         "",                      "",                      "",                        ""}, // sayonara
    {" Eradicator Enhancement Chip ", "",                         "",                      "",                      "",                        ""},
    {"C7ProxyMinePickup",             "C7ProxyMineAmmo",          "",                      "",                      "",                        ""},
    {"RMROxygenRecycler",             "",                         "RMRJetPack",            "",                      "",                        ""},
    {"KatarnSupercharge",             "",                         "",                      "",                      "",                        ""},
    {"IPOGRandomItemGenerator",       "",                         "",                      "",                      "",                        ""},
    {"DisruptorEnergyBall",           "DisruptorPSIEnergy",       "",                      "",                      "",                        ""},
    {"WTStrengthPhial",               "",                         "",                      "",                      "",                        ""},
    {"HL Squeaks",                    "HLSqueakAmmo",             "HL Crossbow",           "Shell",                 "HLOPHasBarnacleLongJump", ""},
    {"SWRipperHeart",                 "HeartAmmo",                "HeatSeekingCard",       "",                      "SWGasGrenade",            ""},
    {"RandomMagicItem",               "",                         "",                      "",                      "",                        ""},
    {"Ring of RA",                    "",                         "",                      "",                      "",                        ""},
    {" Hunting Rifle With Scope ",    "Clip",                     " Chicken Crossbow ",    "ChickenAmmo",           "",                        ""},
    {"Q2GrenadeLauncher",             "RocketAmmo",               "Q2ETFRifle",            "Q2Flechettes",          "Q2Railgun",               "Cell"},
    {"Hexen2TomeOfPower",             "",                         "Hexen2ForceCube",       "",                      "",                        ""},
    {"Goldeneye_SniperRifle",         "Goldeneye_SniperMagazine", "Goldeneye_SilencedD5K", "Goldeneye_D5KMagazine", "Goldeneye_GadgetGranter", ""},
    {"Catacomb_RandomGem",            "",                         "",                      "",                      "",                        ""},
    {"Painkiller_Tarot_SilverGiver",  "",                         "",                      "",                      "",                        ""},
    {"Unreal_GESBioRifle",            "Cell",                     "Unreal_Rifle",          "Shell",                 "Unreal_Duster",           "Clip"},
    {"RTCW_FlameThrower",             "Cell",                     "RTCW_AlliedCrate",      "",                      "RTCW_STEN",               "Clip"},
};

int UniqueMaxes[CLASSCOUNT][CHOICECOUNT_U] = 
{
    {0,     0,      0,  0,		0,	0},
    {0,     0,      0,  0,		0,	0},
    {0,     0,      1,  0,		16,	0},
    {9,     0,      0,  0,		0,	0},
    {16,    0,      0,  0,		0,	0},
    {1,     100,    0,  0,		0,	0},
    {1,     50,     1,  50,		0,	0},
    {1,     0,      0,  0,		0,	0},
	{1,		10,		1,	10,		1,	5}, // added these -- ipfreeley
	{2,     0,      0,  0,		0,	0}, // added this -- blake
	{1,     100,    0,  0,		0,	0},  // added this -- caleb
    {0,     0,      0,  0,		0,	0}, // Added this -- strife	
    //{0,     0,      0,  0,		0,	0}, 
    {2,     0,      0,  0,		0,	0}, // added this -- erad	
    {1,     30,     0,  0,		0,	0}, // added this -- C7		
    {3,     0,      3,  0,		0,	0}, // Added this -- RMR	
    {0,     0,      0,  0,		0,	0},	
	{5,		0,		0,	0,		0,	0}, //+Added	
	{20,	0,		0,	0,		0,	0}, //+Added
	{2,		0,		0,	0,		0,	0}, //+Added
	{9,		0,		0,	0,		0,	0}, //+Added	
	{1,     5,      2,  0,		0,	0}, // added this -- Lo Wang
    {0,     0,      0,  0,		0,	0},
    {0,     0,      0,  0,		0,	0},
    {0,     0,      0,  0,		0,	0},
	{0,     0,      0,  0,		0,	0},
	{20,    0,     20,  0,		0,	0},
	{0,     0,      0,  0,		0,	0},
	{0,     0,      0,  0,		0,	0},	
	{0,     0,      0,  0,		0,	0},
	{0,     0,      0,  0,		0,	0},		
	{0,     0,      0,  0,		0,	0},		
};

int UniqueCounts[CLASSCOUNT][CHOICECOUNT_U] =
{
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,     0,     -1, -1,     -1, -1},
	{-1,	-1,		-1, -1,     -1, -1}, // added these -- ip freeley
	{-1,    -1,     -1, -1,     -1, -1}, // added these -- blake
	{-1,    -1,     -1, -1,     -1, -1}, // added these -- caleb
    {-1,    -1,     -1, -1,     -1, -1}, // Added this -- strife	
//    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},	
    {-1,    -1,     -1, -1,     -1, -1},	
	{-1,    -1,     -1, -1,     -1, -1}, //+Added	
	{-1,    -1,     -1, -1,     -1, -1}, //+Added	
	{-1,    -1,     -1, -1,     -1, -1}, //+Added
	{-1,    -1,     -1, -1,     -1, -1}, //+Added	
	{-1,    -1,     -1, -1,     -1, -1}, // Added this -- lwang		
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},
    {-1,    -1,     -1, -1,     -1, -1},	
	{-1,    -1,     -1, -1,     -1, -1},
	{-1,    -1,     -1, -1,     -1, -1},
	{-1,    -1,     -1, -1,     -1, -1},
	{-1,    -1,     -1, -1,     -1, -1},	
	{-1,    -1,     -1, -1,     -1, -1},
	{-1,    -1,     -1, -1,     -1, -1},
	{-1,    -1,     -1, -1,     -1, -1},	
};

int UniqueScripts[CLASSCOUNT] = {0, 0, 0, 0, 0, 0, SAMSARA_MARATHON, 0, 0, 0};

int ClassWeapons[CLASSCOUNT][SLOTCOUNT][CHOICECOUNT] = 
{
    {   // Doomguy
        {" Fist ",                          "",             "",             "", ""},
        {" Chainsaw ",                      "",             "",             "", ""},
        {" Pistol ",                        "",             "",             "", ""},
        {" Shotgun ",                       "Shell",        "",             "", ""},
        {"Super Shotgun",                   "Shell",        "",             "", ""},
        {" Chaingun ",                      "Clip",         "",             "", ""},
        {"Rocket Launcher",                 "RocketAmmo",   "",             "", ""},
        {"Plasma Rifle",                    "Cell",         "",             "", ""},
        {"B.F.G. 9000",                     "Cell",         "",             "", ""},
		{" Minigun ",                     	"Clip",         "",             "", ""},
		{" GrenadeLauncher ",               "RocketAmmo",   "",             "", ""},
		{" Railgun ",               		"Cell",   		"",             "", ""},
		{" BFG10K ",               			"Cell",   		"",             "", ""},
    },

    {   // Chexguy
        {" Bootspoon ",                     "",             "",             "", ""},
        {"Super Bootspork",                 "",             "",             "", ""},
        {"Mini-Zorcher",                    "",             "",             "", ""},
        {"Large Zorcher",                   "Shell",        "",             "", ""},
        {"Super Large Zorcher",             "Shell",        "",             "", ""},
        {"Rapid Zorcher",                   "Clip",         "",             "", ""},
        {"Zorch Propulsor",                 "RocketAmmo",   "",             "", ""},
        {"Phasing Zorcher",                 "Cell",         "",             "", ""},
        {"LAZ Device",                      "Cell",         "",             "", ""},
    },

    {   // Corvus
        {" Staff ",                         "",             "",             "", ""},
        {"Gauntlets of the Necromancer",    "",             "",             "", ""},
        {"Elven Wand",                      "",             "",             "", ""},
        {" Firemace ",                      "Shell",        "",             "", ""},
        {"Ethereal Crossbow",               "Shell",        "",             "", ""},
        {"Dragon Claw",                     "Clip",         "",             "", ""},
        {"Phoenix Rod",                     "RocketAmmo",   "",             "", ""},
        {"Hellstaff",                       "Cell",         "",             "", ""},
        {"DSparilStaff",                    "Cell",             "",             "", ""},
    },

    {   // B.J.
        {"Knife",                           "",             "",             "", ""},
        {"BJSuperKnife",                    "",             "",             "", ""},
        {"Luger",                           "",             "",             "", ""},
        {"Machine Gun",                     "Clip",         "",             "", ""},
        {"Machine Gun",     				"Clip",         "",             "", ""},
        {"  Chaingun  ",                    "Clip",         "",             "", ""},
        {" Rocket Launcher ",               "RocketAmmo",   "",             "", ""},
        {" Flamethrower ",                  "Cell",         "",             "", ""},
        {"Spear of Destiny",                "Cell",         "",             "", ""},
    },

    {   // Parias
        {"Mace of Contrition",              "",             "",             "", ""},
        {"PortFlechette",                   "",             "",             "", ""},
        {"Sapphire Wand",                   "",             "",             "", ""},
        {"Frost Shards",                    "Clip",         "",             "", ""},
        {"Timon's Axe",                     "Clip",         "",             "", ""},
        {"Serpent Staff",                   "Clip",         "",             "", ""},
        {"Hammer of Retribution",           "Cell",         "",             "", ""},
        {"Firestorm",                       "Cell",         "",             "", ""},
        {"Wraithverge",                     "Cell",         "",             "", ""},
    },

    {   // Duke
        {"Mighty Boot",                     "",             "",             "", ""},
        {"Pipebombs",                       "RocketAmmo",   "",             "", ""},
        {"Glock 17",                        "",             "",             "", ""},
        {"  Shotgun  ",                     "Shell",        "",             "", ""},
        {"Explosive Shotgun",               "Shell",   "",             "", ""},
        {"Chaingun Cannon",                 "Clip",         "",             "", ""},
        {"RPG",                             "RocketAmmo",   "",             "", ""},
        {"Freezethrower",                   "Cell",         "",             "", ""},
        {"Devastator Weapon",               "Cell",         "",             "", ""},
    },

    {   // Security Officer
        {"Steel Knuckles",                  "",             "",             "",                 ""},
        {"KKV-7 SMG Flechette",             "Clip",         "",             "",   ""},
        {".44 Magnum Mega Class A1",        "",             "",             "",                 ""},
        {"WSTE-M5 Combat Shotgun",          "Shell",        "",             "",  ""},
        {"Fusion Pistol",                   "Cell", "",         "",                 ""},
        {"MA-75B Assault Rifle",            "Clip",  "RocketAmmo",         "",                 ""},
        {"SPNKR-XP SSM Launcher",           "RocketAmmo",  "",   "",                 ""},
        {"TOZT-7 Napalm Unit",              "Cell", "",         "",                 ""},
        {"ONI-71 Wave Motion Cannon",       "Cell",         "RocketAmmo",   "",                 ""},
    },
	
    {   // Ranger
        {"Axe",                             "",             "",             "",		      ""},
        {"Mjolnir",                         "",             "",             "", 		  ""},
        {"Single Shotgun",                  "",             "",             "",  		  ""},
        {"Double Shotgun",                  "Shell",        "",             "", 		  ""},
        {"Grenade Launcher",                "RocketAmmo",   "",             "",  		  ""},
        {"Nailgun",                         "Clip",         "",             "", 		  ""},
        {"  Rocket Launcher  ",             "RocketAmmo",   "",             "",			  ""},
        {"Super Nailgun",                   "Clip",         "",             "", 		  ""},
        {"Thunderbolt",                     "Cell",         "",             "", ""},
    },
    {   // I.P. Freely
        {"RottKnife",                       "",             "",             "", ""},
        {"Bazooka",                      "HSMissiles",   "Clip",        "", ""},
        {"RPistol",                  		"",             "",             "", ""},
        {"Double Pistols",                  "",    			"",             "", ""},
        {"HeatSeeker",                         "RottMissiles",	"Shell",        "", ""},
        {"MP40",                   			"", 			"",        		"", ""},
        {" FireBomb ",                      "FBMissiles",   "RocketAmmo",   "", ""},
        {"DrunkMissiles",                   "DMissiles",    "Cell",         "", ""},
        {"Flamewall",                       "FWMissiles",   "Cell",         "", ""},
    },
	{	// Blake Stone
        {"",                                "",             "",             "", ""},
        {"BlakeSuperAutoCharge",            "",             "",             "", ""},
        {"Auto Charge Pistol",              "",             "",             "", ""},
        {"Slow Fire Protector",             "Shell",    	"",             "", ""},
        {"Heavy Assault Weapon",             "Shell",    		"",             "", ""},
        {"Rapid Assault Weapon",          "Clip",    		"",             "", ""},
        {"Plasma Discharge Unit",           "RocketAmmo",   "",             "", ""},
        {"Dual Neutron Disruptor",       "Cell",    		"",             "", ""},
        {"Anti-Plasma Cannon",              "Cell",   		"",             "", ""},
	},
	{	// Caleb
        {"Pitchfork",                       "",             "",             "", ""},
        {"Dynamite",                        "RocketAmmo",   "",             "", ""},
        {"   Revolver   ",                  "",             "",             "", ""},
        {"Flaregun",             			"Shell",    	"",             "", ""},
        {"SawedOff",             			"Shell",    	"",             "", ""},
        {"Tommygun",             			"Clip",    		"",             "", ""},
        {"NapalmLauncher",           		"RocketAmmo",   "",             "", ""},
        {"TeslaCannon",          			"Cell",    		"",             "", ""},
        {"LifeLeech",              			"Cell",   		"",             "", ""},	
	},
    {   // Strifeguy
        {"Punch Dagger",                    "",             "",             "", ""}, // Fist
        {"StrifeBeaconItem5",               "",             "",             "", ""}, // Chainsaw
        {"   Pistol   ",                    "",             "",             "", ""}, // Pistol
        {"  Crossbow  ",       				"Shell",        "",             "", ""}, // Shotgun
        {"Mini Missile Launcher",           "RocketAmmo",   "",             "", ""}, // Super Shotgun
        {"Assault Gun",                     "Clip",         "",             "", ""}, // Chaingun
        {" Grenade Launcher ", 				"RocketAmmo",   "",             "", ""}, // Rocket Launcher
        {"Flame Thrower",                   "Cell",         "",             "", ""}, // Plasma Rifle
        {" Mauler ",        				"Cell",         "",             "", ""}, // BFG9000
    },
/*    {   // Doom 64 Guy
        {"  Fist  ",                        "",             "",             "", ""},
        {"  Chainsaw  ",                    "",             "",             "", ""},
        {"  Pistol  ",                      "",             "",             "", ""},
        {"   Shotgun   ",                   "Shell",        "",             "", ""},
        {" Super Shotgun ",                 "Shell",        "",             "", ""},
        {"   Chaingun   ",                  "Clip",         "",             "", ""},
        {"   Rocket Launcher   ",           "RocketAmmo",   "",             "", ""},
        {" Plasma Rifle ",                  "Cell",         "",             "", ""},
        {" B.F.G. 9000 ",                   "Cell",         "",             "", ""},
        {"  Chainsaw  ",                    "",             "",             "", ""},
    },*/
    {   // Eleena
        {"  Claw  ",                        "",             "",             "", ""},
        {" Arachnicator ",                  "RocketAmmo",   "",             "", ""},
        {"  Ripper Disc  ",                 "",             "",             "", ""},
        {"  Sonic Shock  ",                 "Shell",        "",             "", ""},
        {"Pellet Bomb",                 	"Shell",        "",             "", ""},
        {"  Dart Cannon  ",                 "Clip",         "",             "", ""},
        {"    Missile Launcher    ",        "RocketAmmo",   "",             "", ""},
        {"Napalm Charge",                   "Cell",         "",             "", ""},
        {" Plasma Ball ",                   "Cell",         "",             "", ""},
    },
    {   // C7
        {"",                   "",             				"",             "", ""}, // Fist
        {"M24CAW",             "Clip",         				"",             "", ""}, // Chainsaw
        {"Taser",              "",             				"",             "", ""}, // Pistol
        {"M343Vulcan",         "Shell",        				"",             "", ""}, // Shotgun
        {"AssaultShotgun",     "Shell",        				"",             "", ""}, // Super Shotgun
        {"AlienDualBlaster",   "Clip",         				"",             "", ""}, // Chaingun
        {"AlienPlasmaRifle",   "RocketAmmo",   				"",             "", ""}, // Rocket Launcher
        {"AlienAssaultCannon", "Cell",         				"",             "", ""}, // Plasma Rifle
        {"AlienDisintegrator", "Cell",         				"",             "", ""}, // BFG9000
        {"",                   "",             				"",             "", ""}, // Punchdrunk Chainsaw
	},
    {   // RMR
        {"",                			    "",             "",             "", ""}, // Fist
        {"DirtShark",      				    "",         	"",             "", ""}, // Chainsaw
        {" Laser Pistol ",     				"",             "",             "", ""}, // Pistol
        {"ACR Laser Rifle",    				"Shell",        "",             "", ""}, // Shotgun
        {"ACR ADD-ON",     	   				"Shell",        "",             "", ""}, // Super Shotgun
        {"Cyclops Particle Accelerator", 	"Clip", 		"",     		"",	""}, // Chaingun
        {"RMR Grenade Launcher", 			"RocketAmmo", 	"", 			"", ""}, // Rocket Launcher
        {"RMR Railgun", 		 			"Cell",  	   	"",             "", ""}, // Plasma Rifle
        {" RMR Plasma Cannon ",  			"Cell",      	"",             "", ""}, // BFG9000
        {"",                     			"",          	"",             "", ""}, // Punchdrunk Chainsaw
	},	
    {   // Kyle Katarn
        {"  Fist_2x5  ",                    "",             "",             "", ""},
        {"Thermal Detonator",               "RocketAmmo",  	"",             "", ""},
        {"Bryar Pistol",           			"",             "",             "", ""},
        {"Stormtrooper Rifle",              "Clip",        "",             "", ""},
        {"Fusion Cutter",             		"Shell",        "Shell",        "", ""},
        {"Imperial Repeater",         		"Cell",        	"Cell",  	    "", ""},
        {"Mortar Gun",           			"RocketAmmo",   "",             "", ""},
        {"Concussion Rifle",        		"Cell",         "",             "", ""},
        {"Assault Cannon",                  "Shell",         "RocketAmmo",   "", ""},
    },	
	{	//Mooman
		{" Tazer ",							"",				"",				"",	""},
		{"IPOGGrenadeItem",					"",			"",				"",	""},
		{" Aldus Pistol ",					"Clip",			"",				"",	""},
		{" Aldus Flamethrower ",				"Clip",		"",				"",	""},
		{" Plasma Shotgun ",			"Shell",		"",				"",	""},
		{" Fast Chaingun ",					"Clip",			"",				"",	""},
		{" Fast Rocket Launcher ",			"RocketAmmo",	"",				"",	""},
		{" Laser Cannon ",					"Cell",			"",				"",	""},
		{" Super Plasma Annihilator ",		"Cell",			"",				"",	""},
	},	
	{	//Jack
		{"Disruptor Fist",					"",				"",				"",	""},
		{" 18mm Auto ",						"Clip",			"",				"",	""},
		{" 18mm Semi ",						"",				"",				"",	""},
		{" Phase Rifle ",					"Clip",			"",				"",	""},
		{" AM Blaster ",					"Shell",		"",				"",	""},
		{"Phase Repeater",					"Clip",			"",				"",	""},
		{" Lock-on Cannon ",				"RocketAmmo",	"",				"",	""},
		{" AM Cyclone ",					"Shell",		"",				"",	""},
		{" Disruptor Zodiac ",  			"Cell",			"",				"",	""},
	},
	//+Added
	{	// Grondoval
		{"Witchaven_Dagger",					"",				"",				"",	""},
		{"WTShieldTrigger",					"",				"",				"",	""},
		{"Bow and Arrows",					"",				"",				"",	""},
		{"ShortSword",						"Clip",		"",				"",	""},
		{"Battle Axe",						"Shell",		"",				"",	""},
		{"Ice Halberd",						"Clip",			"",				"",	""},
		{"Fire Mace",						"RocketAmmo",	"",				"",	""},
		{"Frozen two-hand sword",			"Cell",			"",				"",	""},
		{"Pike Axe",						"Cell",				"",				"",	""},
	},
	{	//Freebutt
		{"Crowbar",							"",					"",				"",	""},
		{"Hornetgun",						"",				"",				"",	""},
		{"9mm Pistol",						"Clip",		"",			"",	""},
		{"Assault Shotgun",					"Shell",	"",		"",	""},
		{".357 Python",						"Shell",	"",			"",	""},
		{"MP5",								"Clip",		"RocketAmmo",			"",	""},
		{" RPG ",							"RocketAmmo",		"",	"",	""},
		{"Gauss Cannon",					"Cell",				"",				"",	""},
		{"E.G.O.N.",						"Cell",				"",				"",	""},
	},	
    {   // Lo Wang
	    {"SWFists",                    "",             "",            "", ""},
        {"SWSticky",                   "RocketAmmo",   "",            "", ""},
        {"SWShuriken",                 "",             "",            "", ""},
        {"SWRiotgun",                  "Shell",   "",            "", ""},
        {"SWGrenade",                  "RocketAmmo",        "",            "", ""},
        {"SWUzi",                      "Clip",         "",            "", ""},
        {"SWMissileLauncher",          "RocketAmmo",   "",            "", ""},
        {" SWRailgun ",                "Cell",         "",            "", ""},
        {"SWGuardianHead",             "Cell",         "",            "", ""},
	},	
    {   // Cybermage
	    {"MagicFist",                    "",      		 "",            "", ""},
        {"CMDarklightFoil",              "",      		 "",            "", ""},
        {"CMLaserPistol",                "",             "",            "", ""},
        {"CMFusionGun",                  "Shell",   	 "",            "", ""},
        {"CMBlastRifle",                 "Shell",        "",            "", ""},
        {"CMSMG",                      	 "Clip",         "",            "", ""},
        {"CMRocketGun",          		 "RocketAmmo",   "",            "", ""},
        {"CMHVBMG",                		 "Cell",         "",            "", ""},
        {"CMPlasmaGun",             	 "Cell",         "",            "", ""},
	},	
    {   // Jon
	    {"PSMachete",                    "",      		 "",            "", ""},
        {" Anubis Mine ",                "RocketAmmo",	 "",            "", ""},
        {"PSMagnum",                	 "",             "",            "", ""},
        {"ExShotgun",                    "Shell",   	 "",            "", ""},
        {"PSFlamethrower",               "Shell",        "",            "", ""},
        {"PSM60",                      	 "Clip",         "",            "", ""},
        {"PSCobraStaff",          		 "RocketAmmo",   "",            "", ""},
        {"Sacred Manacle",               "Cell",         "",            "", ""},
        {" Mummy Staff ",             	 "Cell",         "",            "", ""},
	},	
    {   // Leonard
	    {" RR Crowbar ",                    "",      		"",            "", ""},
        {" RR Rip Saw ",              		"Shell",      	"",            "", ""},
        {" .454 Casull Pistol ",            "",             "",            "", ""},
        {" RR Hunting Crossbow ",           "Shell",   	 	"",            "", ""},
        {" Scattered Gun ",                 "Shell",        "",            "", ""},
        {" Ranch Rifle ",                   "Clip",         "",            "", ""},
        {" Dyn 'O' Mites ",          	"RocketAmmo",   "",            "", ""},
        {" Alien Bra Gun ",                	"Cell",         "",            "", ""},
        {" Alien Arm Cannon ",             	"Cell",         "",            "", ""},
	},	
	{   // Bitterman
        {"",                   			    "",             "",             "", ""},
        {"Q2MachineGun",                  	"Clip",         "",             "", ""},
        {"Q2Blaster",           			"",             "",             "", ""},
        {"Q2Shotgun",                       "Shell",        "",             "", ""},
        {"Q2SuperShotgun",             	    "Shell",        "",             "", ""},
        {"Q2Chaingun",         		        "Clip",         "",             "", ""},
        {"Q2RocketLauncher",           		"RocketAmmo",   "",             "", ""},
        {"Q2HyperBlaster",        		    "Cell",         "",             "", ""},
        {"Q2BFG10K",                  		"Cell",         "",             "", ""},
    },
	{   // Demoness
		{"Hexen2Sickle",                   	"",             "",             "", ""},
        {"Hexen2IceMace",                  	"Clip",         "",             "", ""},
        {"Hexen2BloodFire",           		"",             "",             "", ""},
        {"Hexen2AcidRune",    			    "Clip",         "",             "", ""},
        {"Hexen2SpellBookMagicMissile",             	    "Clip",         "",             "", ""},
        {"Hexen2SpellBookBoneShard",        "Cell",         "",             "", ""},
        {"Hexen2FireRune",           		"Cell",   		"",             "", ""},
        {"Hexen2RavenStaff",        		"Clip",   		"Cell",   		"", ""},
        {"Hexen2TempestStaff",              "Clip",   		"Cell",   		"", ""},
    },
	{   // Bond
		{"Goldeneye_Slapper",               "",             "",             "", ""},
        {"Goldeneye_ThrowingKnives",        "Goldeneye_ThrowingKnivesAmmo",		"",             "", ""},
        {"Goldeneye_PP7Silenced",           "Clip",            	"",             "", ""},
        {"Goldeneye_KF7Soviet",     		"Clip",         	"",             "", ""},
        {"Goldeneye_AutoShotgun",           "Shell",			"",             "", ""},
        {"Goldeneye_AR33",        			"Clip",         	"",             "", ""},
        {"Goldeneye_RocketLauncher",        "RocketAmmo", 		"",       "", ""},
        {"Goldeneye_RCP90",        			"Cell",   			"",   		"", ""},
        {"Goldeneye_Moonraker",             "Cell",   			"",   		"", ""},
    },
	{   // Petton EverHail
		{"",               	"",             "",         "", ""},
        {"Catacomb_WavesQuickSpell",        		"Catacomb_Waves",		"",         "", ""},
        {"Catacomb3D_MagicMissile",           		"",         "",         "", ""},
        {"Catacomb_XterminatorsQuickSpell",     				"Catacomb_Xterminators",         "",         "", ""},
        {"Catacomb_BurstsQuickSpell",           		"Catacomb_Bursts",		"",         "", ""},
        {"Catacomb_ZappersQuickSpell",        				"Catacomb_Zappers",         "",         "", ""},
        {"Catacomb_NukesQuickSpell",        	"Catacomb_Nukes", 	"",       	"", ""},
        {"Catacomb_BoltsQuickSpell",        		"Catacomb_Bolts",   		"",   		"", ""},
        {"Catacomb_AtomicQuickSpell",             	"Catacomb_Nukes",   		"Catacomb_Xterminators",   		"", ""},
    },	
	{   // Daniel Garner
		{"Painkiller_Painkiller",               	"",             "",         "", ""},
        {"Painkiller_StakeGun",        				"Shell",		"RocketAmmo",         "", ""},
        {"Painkiller_Painkiller",           		"",         "",         "", ""},
        {"Painkiller_Shotgun",     					"Shell",         "Painkiller_FreezerAmmo",         "", ""},
        {"Painkiller_BoltGun",           			"Cell",		"Painkiller_HeaterAmmo",         "", ""},
        {"Painkiller_Rifle",        				"Clip",         "Painkiller_FlamerAmmo",         "", ""},
        {"Painkiller_RocketLauncher",        		"RocketAmmo", 	"Clip",       	"", ""},
        {"Painkiller_Electrodriver",        		"Cell",   		"Painkiller_ElectroAmmo",   		"", ""},
        {"Painkiller_Tarot_GoldGiver",             	"",   		"",   		"", ""},
    },	
	{   // Prisoner 849
		{"Unreal_DispersionPistol",               	"DPistolAmmo",             "",         "", ""},
        {"Unreal_Razorjack",        				"Cell",		"",         "", ""},
        {"Unreal_Automag",           		"Clip",         "",         "", ""},
        {"Unreal_ASMDShockRifle",     					"Shell",         "",         "", ""},
        {"Unreal_FlakCannon",           			"Shell",		"",         "", ""},
        {"Unreal_Stinger",        				"Clip",         "Clip",         "", ""},
        {"Unreal_Eightball",        		"RocketAmmo", 	"RocketAmmo",       	"", ""},
        {"Unreal_Minigun",        		"Cell",   		"",   		"", ""},
        {"Unreal_Redeemer",             	"Cell",   		"",   		"", ""},
    },	
	{   // RTCW BJ
		{"RTCW_Knife",               	"",             "",         "", ""},
        {"RTCW_Grenade",        				"RocketAmmo",		"",         "", ""},
        {"RTCW_Luger",           		"RTCW_LugerMagazine",         "Clip",         "", ""},
        {"RTCW_MP40",     					"RTCW_MP40Magazine",         "Clip",         "", ""},
        {"RTCW_Mauser",           			"RTCW_MauserMagazine",		"Shell",         "", ""},
        {"RTCW_FG42",        				"RTCW_FG42Magazine",         "Clip",         "", ""},
        {"RTCW_Panzerfaust",        		"RocketAmmo", 	"",       	"", ""},
        {"RTCW_Venom",        		"RTCW_VenomMagazine",   		"Cell",   		"", ""},
        {"RTCW_TeslaGun",             	"Cell",   		"",   		"", ""},
    },	
};

int weaponConditionScripts[CLASSCOUNT][SLOTCOUNT] = {
	{ 0, 0, 0, 0, 0, 26, 28, 30, 32, 27, 29, 31, 33 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 1, 0, 2, 3, 4, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 19, 0, 20, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 23 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 24 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 5, 0, 6, 7, 8, 9, 10, 11 },
	{ 0, 0, 0, 0, 0, 21, 0, 0, 25 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 12, 0, 13, 14, 15, 16, 17, 18 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 },	
};

#define SAMSARA_RGP_PAGES	2
str SamsaraRGP[CLASSCOUNT][SAMSARA_RGP_PAGES] =
{
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"SpnkrBeam",		"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},	
	{"PGArrowTrail",	"PGSuperPlasmaTrail"},
	{"",				"",},	
	{"WTGrenadeTrail",	"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},
	{"",				"",},	
	{"",				"",},	
	{"",				"",},
	{"",				"",},	
	{"",				"",},	
	{"",				"",},		
};

#define SAMSARA_RGP_PROPERTIES	2
#define SAMSARA_RGP_HASDELAY 0
#define SAMSARA_RGP_DISTANCE 1
int SamsaraRGPProperties[CLASSCOUNT][SAMSARA_RGP_PAGES][SAMSARA_RGP_PROPERTIES] =
{
	{{0,	0},			{0,		0},},
	{{0,	0},			{0,		0},},
	{{0,	0},			{0,		0},},
	{{0,	0},			{0,		0},},
	{{0,	0},			{0,		0},},
	{{0,	0},			{0,		0},},
	{{1,	8},			{0,		0},},
	{{0,	0},			{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
//	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},	
	{{1,	32},		{0,		16},},
	{{0,	0}, 		{0,		0},},
	{{1,	10},		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},
	{{0,	0}, 		{0,		0},},	
	{{0,	0}, 		{0,		0},},	
	{{0,	0}, 		{0,		0},},	
	{{0,	0}, 		{0,		0},},	
	{{0,	0}, 		{0,		0},},	
	{{0,	0}, 		{0,		0},},	
};

str ClassHotKeyWeapon[CLASSCOUNT][MAXMODES][SLOTCOUNT+3] = 
{
	{
        {" Fist ", " Chainsaw ", " Pistol ", " Shotgun ", "Super Shotgun", " Chaingun ", "Rocket Launcher", "Plasma Rifle", "B.F.G. 9000", "", "", "", " Minigun ", " GrenadeLauncher ", " Railgun ", " BFG10K "},
		{" Fist ", " Chainsaw ", " Pistol ", " Shotgun ", "Super Shotgun", " Chaingun ", "Rocket Launcher", "Plasma Rifle", "B.F.G. 9000", "", "", "", "",          "",                  "",          ""        },
    },
	{
        {" Bootspoon ", "Super Bootspork", "Mini-Zorcher", "Large Zorcher", "Super Large Zorcher", "Rapid Zorcher", "Zorch Propulsor", "Phasing Zorcher", "LAZ Device"},
	},
	{
		{" Staff ", "Gauntlets of the Necromancer", "Elven Wand", " Firemace ", "Ethereal Crossbow", "Dragon Claw", "Phoenix Rod", "Hellstaff", "DSparilStaff", "PortTomeCoOp", "Grim Ballista", "SamsaraCorvusArtiEgg"},
	},
	{
		{"Knife", "",                 "Luger", "Machine Gun", "",                "  Chaingun  ", " Rocket Launcher ", " Flamethrower ", "Spear Of Destiny", "",                       "",               ""                },
		{"Knife", "",                 "Luger", "Machine Gun", "",                "  Chaingun  ", " Rocket Launcher ", " Flamethrower ", "Spear Of Destiny", "",                       "",               ""                },
		{"Knife", "Totenkopf_Mauser", "Luger", "Machine Gun", "Totenkopf_STG44", "  Chaingun  ", " Rocket Launcher ", " Flamethrower ", "Spear Of Destiny", "Totenkopf_FlameThrower", "Totenkopf_MG42", "Totenkopf_Sniper"},
	},
	{
		{"Mace of Contrition", "PortFlechette", "Sapphire Wand", "Frost Shards", "Timon's Axe", "Serpent Staff", "Hammer of Retribution", "Firestorm", "Wraithverge", "PortMysticAmbit"},
		{"Mace of Contrition", "PortFlechette", "Sapphire Wand", "Frost Shards", "Timon's Axe", "Serpent Staff", "Hammer of Retribution", "Firestorm", "Wraithverge", "PortMysticAmbit"},
		{"Mace of Contrition", "PortFlechette", "Sapphire Wand", "Frost Shards", "Timon's Axe", "Serpent Staff", "Hammer of Retribution", "Firestorm", "Wraithverge", "PortMysticAmbit"},
	},
	{
		{"Mighty Boot", "Pipebombs", "Glock 17", "  Shotgun  ", "Explosive Shotgun", "Chaingun Cannon", "RPG", "FreezeThrower", "Devastator Weapon", "DukePortJetpack", "Shrinker", "Expander"},
		{"Mighty Boot", "Pipebombs", "Glock 17", "  Shotgun  ", "Explosive Shotgun", "Chaingun Cannon", "RPG", "FreezeThrower", "Devastator Weapon", "DukePortJetpack", "Shrinker", "Expander"},
	},
	{
		{"Steel Knuckles", "KKV-7 SMG Flechette", ".44 Magnum Mega Class A1", "WSTE-M5 Combat Shotgun", "Fusion Pistol", "MA-75B Assault Rifle", "SPNKR-XP SSM Launcher", "TOZT-7 Napalm Unit", "ONI-71 Wave Motion Cannon", "Alien Weapon",  " Alien Weapon "},
	},
	{
		{"Axe", "Mjolnir", "Single Shotgun", "Double Shotgun", "Grenade Launcher", "Nailgun", "  Rocket Launcher  ", "Super Nailgun", "Thunderbolt", "Laser Cannon"},
	},
	{
		{"RottKnife", "Bazooka", "RPistol", "Double Pistols", "HeatSeeker", "MP40", " Firebomb ", "DrunkMissiles", "FlameWall", "Excalibat", "Split Missile", "Dark Staff"},
		{"RottKnife", "Bazooka", "RPistol", "Double Pistols", "HeatSeeker", "MP40", " Firebomb ", "DrunkMissiles", "FlameWall", "Excalibat", "Split Missile", "Dark Staff"},
		{"RottKnife", "Bazooka", "RPistol", "Double Pistols", "HeatSeeker", "MP40", " Firebomb ", "DrunkMissiles", "FlameWall", "Excalibat", "Split Missile", "Dark Staff"},
		{"RottKnife", "Bazooka", "RPistol", "Double Pistols", "HeatSeeker", "MP40", " Firebomb ", "DrunkMissiles", "FlameWall", "Excalibat", "Split Missile", "Dark Staff"},
		{"RottKnife", "Bazooka", "RPistol", "Double Pistols", "HeatSeeker", "MP40", " Firebomb ", "DrunkMissiles", "FlameWall", "Excalibat", "Split Missile", "Dark Staff"},
	},
	{
		{"", "", "Auto Charge Pistol", "Slow Fire Protector", "Heavy Assault Weapon", "Rapid Assault Weapon", "Plasma Discharge Unit", "Dual Neutron Disruptor", "Anti-Plasma Cannon", "BlakeRefill"},
		{"", "", "Auto Charge Pistol", "Slow Fire Protector", "Heavy Assault Weapon", "Rapid Assault Weapon", "Plasma Discharge Unit", "Dual Neutron Disruptor", "Anti-Plasma Cannon", "BlakeRefill"},
	},
	{
		{"Pitchfork", "Dynamite", "   Revolver   ", "Flaregun", "SawedOff", "Tommygun", "NapalmLauncher", "TeslaCannon", "LifeLeech", "VoodooDoll", "", "Spraycan"},
	},
	{
		{"Punch Dagger", "StrifeBeaconItem5", "   Pistol   ", "  Crossbow  ", "Mini Missile Launcher", "Assault Gun", " Grenade Launcher ", "Flame Thrower", " Mauler ", "", "", "", " Sigil "},
	},
	{
		{"  Claw  ", " Arachnicator ",  "  Ripper Disc  ", "  Sonic Shock  ", "Pellet Bomb", "  Dart Cannon  ",  "    Missile Launcher    ", "Napalm Charge", " Plasma Ball ", " Eradicator Enhancement Chip "},
	},
	{
		{"", "M24CAW", "Taser", "M343Vulcan", "AssaultShotgun", "AlienDualBlaster", "AlienPlasmaRifle", "AlienAssaultCannon", "AlienDisintegrator"},
	},
	{
		{"", "DirtShark", " Laser Pistol ", "ACR Laser Rifle", "ACR ADD-ON", "Cyclops Particle Accelerator", "RMR Grenade Launcher", "RMR Railgun", " RMR Plasma Cannon ", "RMROxygenRecycler", "RMRJetPack", "", "Subestron Arm"},
	},
	{
		{"  Fist_2x5  ", "Thermal Detonator", "Bryar Pistol", "Stormtrooper Rifle", "Fusion Cutter", "Imperial Repeater", "Mortar Gun", "Concussion Rifle", "Assault Cannon", "DFSuperCharge"},
	},
	{
		{" Tazer ", "", " Aldus Pistol ", " Aldus Flamethrower ", " Plasma Shotgun ", " Fast Chaingun ", " Fast Rocket Launcher ", " Laser Cannon ", " Super Plasma Annihilator "},
		{" Tazer ", "", " Aldus Pistol ", " Aldus Flamethrower ", " Plasma Shotgun ", " Fast Chaingun ", " Fast Rocket Launcher ", " Laser Cannon ", " Super Plasma Annihilator "},
		{" Tazer ", "", " Aldus Pistol ", " Aldus Flamethrower ", " Plasma Shotgun ", " Fast Chaingun ", " Fast Rocket Launcher ", " Laser Cannon ", " Super Plasma Annihilator "},
		{" Tazer ", "", " Aldus Pistol ", " Aldus Flamethrower ", " Plasma Shotgun ", " Fast Chaingun ", " Fast Rocket Launcher ", " Laser Cannon ", " Super Plasma Annihilator "},
		{" Tazer ", "", " Aldus Pistol ", " Aldus Flamethrower ", " Plasma Shotgun ", " Fast Chaingun ", " Fast Rocket Launcher ", " Laser Cannon ", " Super Plasma Annihilator "},
	},
	{
		{"Disruptor Fist", " 18mm Auto ", " 18mm Semi ", " Phase Rifle ", " AM Blaster ", "Phase Repeater", " Lock-On Cannon ", " AM Cyclone ", " Disruptor Zodiac ", "DisruptorEnergyBall", "", "", " Disruptor Plasmalance "},
	},
	{
		{"Witchaven_Dagger", "", "Bow and Arrows", "Shortsword", "Battle Axe", "Ice Halberd", "Fire Mace", "Frozen Two-Hand Sword", "Pike Axe", "WTStrengthPhial"},
	},
	{
		{"Crowbar", "Hornetgun", "9mm Pistol", "Assault Shotgun", ".357 Python", "MP5", " RPG ", "Gauss Cannon", "E.G.O.N.", "HL Squeaks", "HL Crossbow", "HLOPBarnacle"},
		{"Crowbar", "Hornetgun", "9mm Pistol", "Assault Shotgun", ".357 Python", "MP5", " RPG ", "Gauss Cannon", "E.G.O.N.", "HL Squeaks", "HL Crossbow", "HLOPBarnacle"},
	},
	{
		{"SWKatana", "SWSticky", "SWShuriken", "SWRiotgun", "SWGrenade", "SWUzi", "SWMissileLauncher", " SWRailgun ", "SWGuardianHead", "SWRipperHeart", "HeatSeekingCard", "SWGasGrenade"},
	},
	{
		{"MagicFist", "CMDarklightFoil", "CMLaserPistol", "CMFusionGun", "CMBlastRifle", "CMSMG", "CMRocketGun", "CMHVBMG", "CMPlasmaGun"},
	},	
	{
		{"PSMachete", " Anubis Mine ", "PSMagnum", "ExShotgun", "PSFlamethrower", "PSM60", "PSCobraStaff", "Sacred Manacle", " Mummy Staff ", "Ring Of RA"},
	},	
	{
		{" RR Crowbar ", " RR Rip Saw ", " .454 Casull Pistol ", " RR Hunting Crossbow ", " Scattered Gun ", " Ranch Rifle ", " Dyn 'O' Mites ", " Alien Bra Gun ", " Alien Arm Cannon ", " Hunting Rifle With Scope ", " Chicken Crossbow "},
	},	
	{
		{"", "Q2Machinegun", "Q2Blaster", "Q2Shotgun", "Q2SuperShotgun", "Q2Chaingun", "Q2RocketLauncher", "Q2HyperBlaster", "Q2BFG10K", "Q2GrenadeLauncher", "Q2ETFRifle", "Q2Railgun"}
	},	
	{
		{"Hexen2Sickle", "Hexen2IceMace", "Hexen2BloodFire", "Hexen2AcidRune", "Hexen2SpellBookMagicMissile", "Hexen2SpellBookBoneShard", "Hexen2FireRune", "Hexen2RavenStaff", "Hexen2TempestStaff", "Hexen2TomeOfPower", "Hexen2ForceCube"},
	},
	{
		{"Goldeneye_Slapper", "Goldeneye_ThrowingKnives", "Goldeneye_PP7Silenced", "Goldeneye_KF7Soviet", "Goldeneye_AutoShotgun", "Goldeneye_AR33", "Goldeneye_RocketLauncher", "Goldeneye_RCP90", "Goldeneye_Moonraker", "Goldeneye_SniperRifle", "Goldeneye_SilencedD5K", "Goldeneye_RemoteMines"},
	},
	{
		{"", "Catacomb_WavesQuickSpell", "Catacomb3D_MagicMissile", "Catacomb_XterminatorsQuickSpell", "Catacomb_BurstsQuickSpell", "Catacomb_ZappersQuickSpell", "Catacomb_NukesQuickSpell", "Catacomb_BoltsQuickSpell", "Catacomb_AtomicQuickSpell"},
	},
	{
		{"Painkiller_Painkiller", "Painkiller_Stakegun", "", "Painkiller_Shotgun", "Painkiller_Boltgun", "Painkiller_Rifle", "Painkiller_RocketLauncher", "Painkiller_Electrodriver"},
	},
	{
		{"Unreal_DispersionPistol", "Unreal_Razorjack", "Unreal_Automag", "Unreal_ASMDShockRifle", "Unreal_FlakCannon", "Unreal_Stinger", "Unreal_Eightball", "Unreal_Minigun", "Unreal_Redeemer", "Unreal_GESBioRifle", "Unreal_Rifle", "Unreal_Duster"},
	},
	{
		{"RTCW_Knife", "RTCW_Grenade", "RTCW_Luger", "RTCW_MP40", "RTCW_Mauser", "RTCW_FG42", "RTCW_Panzerfaust", "RTCW_Venom", "RTCW_TeslaGun", "RTCW_FlameThrower", "", "RTCW_STEN"},
	},
};