script "EleenaTauntCooldown" (void) //610
{
    while (CheckInventory("EleenaTauntCooldown") > 0)
    {
        Delay(35);
        TakeInventory("EleenaTauntCooldown", 1);
    }
}

Script "EleenaBallGag" (int type) NET //612
{
	if(CheckInventory("EleenaBallgag"))
	{
		TakeInventory("EleenaBallgag", 1);
		Print(s:"Ballgag Off");
	}
	else
	{
		GiveInventory("EleenaBallGag", 1);
		Print(s:"Ballgag On");
	}
}
